**Practical no.4**

**Hypothesis Testing**
**a) Formulate null and alternative hypotheses for a given problem.**

**b) Conduct a hypothesis test using appropriate statistical tests (e.g., t-test, chi-square test).**

**c) Interpret the results and draw conclusions based on the test outcomes.**

**T114 | Bhumika Shelar**

**t-test**

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats

In [2]:
df = pd.read_csv("/content/Covid Data.csv")

In [3]:
df.head()

USMER  MEDICAL_UNIT  SEX  PATIENT_TYPE   DATE_DIED  INTUBED  PNEUMONIA  \
0      2             1    1             1  03/05/2020       97          1   
1      2             1    2             1  03/06/2020       97          1   
2      2             1    2             2  09/06/2020        1          2   
3      2             1    1             1  12/06/2020       97          2   
4      2             1    2             1  21/06/2020       97          2   

   AGE  PREGNANT  DIABETES  ...  ASTHMA  INMSUPR  HIPERTENSION  OTHER_DISEASE  \
0   65         2         2  ...       2        2             1              2   
1   72        97         2  ...       2        2             1              2   
2   55        97         1  ...       2        2             2              2   
3   53         2         2  ...       2        2             2              2   
4   68        97         1  ...       2        2             1              2   

   CARDIOVASCULAR  OBESITY  RENAL_CHRONIC  TOBACCO  CLASIFFICATION_FINAL  ICU  
0               2        2              2        2                     3   97  
1               2        1              1        2                     5   97  
2               2        2              2        2                     3    2  
3               2        2              2        2                     7   97  
4               2        2              2        2                     3   97  

[5 rows x 21 columns]

In [5]:
print(df.columns)

Index(['USMER', 'MEDICAL_UNIT', 'SEX', 'PATIENT_TYPE', 'DATE_DIED', 'INTUBED',
       'PNEUMONIA', 'AGE', 'PREGNANT', 'DIABETES', 'COPD', 'ASTHMA', 'INMSUPR',
       'HIPERTENSION', 'OTHER_DISEASE', 'CARDIOVASCULAR', 'OBESITY',
       'RENAL_CHRONIC', 'TOBACCO', 'CLASIFFICATION_FINAL', 'ICU'],
      dtype='object')


In [9]:
data = df["AGE"].dropna().values
print("Data:", data)

Data: [65 72 55 ... 55 28 52]


In [10]:
# Define the null hypothesis
H0 = "The average AGE is 32."
H1 = "The average AGE is more than 32."

print("Null Hypothesis:", H0)
print("Alternative Hypothesis:", H1)

Null Hypothesis: The average AGE is 32.
Alternative Hypothesis: The average AGE is more than 32.


In [11]:
# Calculate the test statistic comparing mean AGE to 32
t_stat, p_value_two_tailed = stats.ttest_1samp(data, 32)

print("T-Statistic:", t_stat)
print("P-Value (Two-Tailed):", p_value_two_tailed)

T-Statistic: 593.1818349458922
P-Value (Two-Tailed): 0.0


In [12]:
# Convert two-tailed p-value to one-tailed (because H1 is "greater than 32")
p_value = p_value_two_tailed / 2

print("T-Statistic:", t_stat)
print("Two-Tailed P-Value:", p_value_two_tailed)
print("One-Tailed P-Value:", p_value)

T-Statistic: 593.1818349458922
Two-Tailed P-Value: 0.0
One-Tailed P-Value: 0.0


In [13]:
# Print results
print("Test statistic:", t_stat)
print("One-tailed p-value:", p_value)

Test statistic: 593.1818349458922
One-tailed p-value: 0.0


In [14]:
# Conclusion
if t_stat > 0 and p_value < 0.05:
    print("Reject the null hypothesis.")
else:
    print("Fail to reject the null hypothesis.")

Reject the null hypothesis.


**Two sampled T-test**

In [15]:
from scipy.stats import ttest_ind
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv("/content/Covid Data.csv")

In [21]:
# Select groups based on PNEUMONIA status
# First, let's check the unique values in 'PNEUMONIA' to ensure the filtering condition is correct.
print(df['PNEUMONIA'].unique())

# Assuming 2 represents 'No Pneumonia' based on common encoding practices for binary categories (1 for Yes, 2 for No, 97/99 for missing/not applicable)
group1 = df[df["PNEUMONIA"] == 2]["AGE"].dropna().values   # No Pneumonia
group2 = df[df["PNEUMONIA"] == 1]["AGE"].dropna().values   # Pneumonia positive
print("Group 1 data (No Pneumonia):")
print(group1)
print("Group 2 data (Pneumonia Positive):")
print(group2)

[ 1  2 99]
Group 1 data (No Pneumonia):
[55 53 68 ... 55 28 52]
Group 2 data (Pneumonia Positive):
[65 72 40 ... 50 61 63]


In [22]:
# Means
group1_mean = np.mean(group1)
group2_mean = np.mean(group2)

print("Group 1 mean value:", group1_mean)
print("Group 2 mean value:", group2_mean)

Group 1 mean value: 40.06715150347214
Group 2 mean value: 53.813914794555764


In [27]:
# Standard deviations
group1_std = np.std(group1)
group2_std = np.std(group2)
print("group1 std value:", group1_std)
print("group2 std value:", group2_std)

group1 std value: 15.737840681587777
group2 std value: 18.209548412617103


In [28]:
# Independent t-test
ttest, pval = ttest_ind(group1, group2, equal_var=False)  # safer for unequal sample sizes
print("p-value:", pval)

p-value: 0.0


In [29]:
# Conclusion
if pval < 0.05:
    print("we reject null hypothesis")
else:
    print("we accept null hypothesis")

we reject null hypothesis


**Paired sampled t-test**

In [30]:
import pandas as pd
from scipy import stats

In [31]:
# Describe AGE and PNEUMONIA
print(df[['AGE', 'PNEUMONIA']].describe())

                AGE     PNEUMONIA
count  1.048575e+06  1.048575e+06
mean   4.179410e+01  3.346831e+00
std    1.690739e+01  1.191288e+01
min    0.000000e+00  1.000000e+00
25%    3.000000e+01  2.000000e+00
50%    4.000000e+01  2.000000e+00
75%    5.300000e+01  2.000000e+00
max    1.210000e+02  9.900000e+01


In [32]:
# Paired t-test (Before vs After for same customers)
ttest, pval = stats.ttest_rel(df['AGE'], df['PNEUMONIA'], nan_policy='omit')
print("p-value:", pval)

p-value: 0.0


In [33]:
# Conclusion
if pval < 0.05:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

reject null hypothesis


You would use a Z test if:

Your sample size is greater than 30. Otherwise, use a t test.

Data points should be independent from each other. In other words, one data point isn’t related or doesn’t affect another data point.

Your data should be normally distributed. However, for large sample sizes (over 30) this doesn’t always matter.

Your data should be randomly selected from a population, where each item has an equal chance of being selected.

Sample sizes should be equal if at all possible.


In [35]:
import pandas as pd
from scipy import stats
from statsmodels.stats import weightstats as stests

# Load dataset
df = pd.read_csv("Covid Data.csv")

# Run one-sample Z-test on AGE
ztest, pval = stests.ztest(df['AGE'].dropna(),
                           x2=None,
                           value=32)  # hypothesized mean

print("p-value:", float(pval))
# Conclusion
if pval < 0.05:
    print("Reject null hypothesis")
else:
    print("Fail to reject null hypothesis")

p-value: 0.0
Reject null hypothesis


**Two-sample Z test**

In [37]:
import pandas as pd
from statsmodels.stats import weightstats as stests

# Load dataset
df = pd.read_csv("Covid Data.csv")

# Paired Z-test: Sales_Before vs Sales_After
ztest, pval1 = stests.ztest(df['AGE'].dropna(),
                            x2=df['PNEUMONIA'].dropna(),
                            value=0,
                            alternative='two-sided')

print(float(pval1))

# Conclusion
if pval1 < 0.05:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")


0.0
reject null hypothesis


**Chi-Square Test**

In [42]:
import pandas as pd
from scipy.stats import chi2_contingency

# Load your dataset
df = pd.read_csv('Covid Data.csv')

# Create a contingency table
contingency_table = pd.crosstab(df['PATIENT_TYPE'], df['PNEUMONIA'])

# Perform the chi-square test
chi2_statistic, p_value, dof, expected_frequencies = chi2_contingency(contingency_table)

# Print the results
print('Chi-square statistic:', chi2_statistic)
print('P-value:', p_value)
print('Degrees of freedom:', dof)
print('Expected frequencies:')
print(expected_frequencies)


Chi-square statistic: 439251.3847492436
P-value: 0.0
Degrees of freedom: 2
Expected frequencies:
[[113323.70566912 722270.1003705   12950.19396037]
 [ 26714.29433088 170263.8996295    3052.80603963]]
